# os: osx
# language: generic

# before_install:
#   - brew update

# install:
#   - mkdir -p $(brew --repo)/Library/Taps/randy3k
#   - ln -s $PWD $(brew --repo)/Library/Taps/randy3k/homebrew-rstudio-server
#   - brew tap --repair

# script:
#   - mkdir -p /tmp/bottles
#   - cd /tmp/bottles
#   - brew test-bot --skip-setup -v

# after_success:
#   - sh deploy.sh
